### ISSUE TITLE
怎么通过命令行的方式使用pbts呢？

### ISSUE THREAD

**Issue by ankisme** [brandonxiang/pb-to-typescript#11]
我有一个文件Test.proto，想通过命令行转成Test.ts，所以我试着依照https://github.com/brandonxiang/pb-to-typescript/tree/main/packages/cli 的步骤来操作，然后碰到了挺多提示错误的，感觉我的用法好像出现了问题

1. 一开始我执行了`npm i pbts-cli`，结果出现了`node_modules`文件夹，但是我执行`pbts`会提示找不到命令
2. 于是我试着执行`npm i pbts-cli -g`命令，这时，我执行`pbts convert -i Test.proto -o Test.ts`仍然提示找不到pbts命令
3. 接着我试着输入`pbts-cli -h`，屏幕上显示如下提示，这些提示跟里的说明不太一样

```
Usage: pb-cli [options] [command]

Options:
  -v, --version             output the version number
  -h, --help                output usage information

Commands:
  build [options] <target>  构建proto js/ts文件
```

4. 我又试着执行`pbts-cli build Test.proto`，则出现了一大堆奇怪的报错

我对nodejs并不熟悉，是否是我的操作有误呢，怎么才能直接通过命令行使用pbts呢？

**Comment by brandonxiang** [comment]
sorry，代码有点问题。

麻烦按照新的文档操作。

可以直接使用
```
npx pbts convert -i packages/cli/__tests__/__fixtures__/input/app/single.proto -o packages/cli/__tests__/__fixtures__/output/single.ts
```
https://github.com/brandonxiang/pb-to-typescript/blob/main/packages/cli/README.md
