### ISSUE TITLE
[feature request] support transform `optional` and `oneof` keyword?

### ISSUE THREAD

**Issue by moecasts** [brandonxiang/pb-to-typescript#14]
Is it possible to auto detect `optional` and `oneof` keywords and add `?` to the export `type` ?
eg:
```protobuf
message Person {
  string name = 1;
  optional uint32 age = 2;
  oneof test_oneof {
    string test_a = 3;
    string test_b = 4;
  }
}
```
to:
```ts
export interface Person {
  name: string;
  sex?: number;
  testA?: string;
  testB?: string;
}
```

**Comment by moecasts** [comment]
@brandonxiang 3.15 开始支持了，case 还挺多的，有时候某个字段确实是可选的。

FYI: https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0#:~:text=Protocol%20Compiler-,Optional,-fields%20for%20proto3

**Comment by brandonxiang** [comment]
@moecasts 默认是optional吧？我用protobuf js试是这样的，有相关资料吗？

**Comment by brandonxiang** [comment]
https://pb.brandonxiang.top/ 你看看现在能否满足你的要求

**Comment by moecasts** [comment]
> https://pb.brandonxiang.top/ 你看看现在能否满足你的要求

可以的，感谢大佬支持！
