### ISSUE TITLE
多个 message 结构体中里面 定义 同名的 Data message , 生成的 ts 文件的时候，没有自动带上 父级的 message 名称

### ISSUE THREAD

**Issue by jjeejj** [brandonxiang/pb-to-typescript#16]
message Message1 {
  message Data {
    int32 id = 1;
  }
  Data data = 3;
}

message Message2 {
  message Data {
    int32 id = 1;
  }
  Data data = 3;
}

生成的 ts 文件 ，会有 2个 同级别的 Data interface 的定义

**Comment by brandonxiang** [comment]
https://github.com/brandonxiang/pb-to-typescript/commit/8bc78905036d4f3490bdd10de08cabf3328bd77c
